import type { Category, GlobalOption, Inspiration, Product } from '../types';

// ============================================================
// CATEGORIES
// ============================================================
export const mockCategories: Category[] = [
  { id: 'cat-1', tenant_id: 'tenant-1', name: 'Perfumaria', slug: 'perfumaria', description: 'Fragrâncias marcantes e delicadas nacionais e importadas', image_url: '/images/insp-perfumes.jpg', order: 1, active: true },
  { id: 'cat-2', tenant_id: 'tenant-1', name: 'Maquiagem', slug: 'maquiagem', description: 'Bases, batons, sombras e corretivos de alta qualidade', image_url: '/images/base-marykay.jpg', order: 2, active: true },
  { id: 'cat-3', tenant_id: 'tenant-1', name: 'Cuidados Diários', slug: 'cuidados-diarios', description: 'Hidratantes corporais, sabonetes e óleos de banho', image_url: '/images/cuidados-creme.jpg', order: 3, active: true },
  { id: 'cat-4', tenant_id: 'tenant-1', name: 'Cuidados Faciais', slug: 'cuidados-faciais', description: 'Séruns, protetor solar e rotinas de skincare', image_url: '/images/routine-serum.jpg', order: 4, active: true },
  { id: 'cat-5', tenant_id: 'tenant-1', name: 'Cabelos', slug: 'cabelos', description: 'Shampoos, condicionadores e máscaras de tratamento', image_url: '/images/shampoo-siage.jpg', order: 5, active: true },
  { id: 'cat-6', tenant_id: 'tenant-1', name: 'Kits e Presentes', slug: 'kits-e-presentes', description: 'Combinações exclusivas em lindas embalagens', image_url: '/images/kit-presente.jpg', order: 6, active: true },
];

// ============================================================
// GLOBAL OPTIONS (Customizações)
// ============================================================
export const mockGlobalOptions: GlobalOption[] = [
  // Cores/Tons de Batom e Maquiagem (Cor)
  { id: 'opt-1', tenant_id: 'tenant-1', type: 'color', name: 'Vermelho Intenso', value: 'Vermelho Intenso', extra: { hex: '#B82626', price_modifier: 0 }, active: true },
  { id: 'opt-2', tenant_id: 'tenant-1', type: 'color', name: 'Nude Clássico', value: 'Nude Clássico', extra: { hex: '#D1A598', price_modifier: 0 }, active: true },
  { id: 'opt-3', tenant_id: 'tenant-1', type: 'color', name: 'Matte Terracota', value: 'Matte Terracota', extra: { hex: '#AC5A46', price_modifier: 0 }, active: true },
  { id: 'opt-4', tenant_id: 'tenant-1', type: 'color', name: 'Rosa Delicado', value: 'Rosa Delicado', extra: { hex: '#E297A6', price_modifier: 0 }, active: true },
  { id: 'opt-5', tenant_id: 'tenant-1', type: 'color', name: 'Base Claro 1', value: 'Claro 1', extra: { hex: '#F4D0B6', price_modifier: 0 }, active: true },
  { id: 'opt-6', tenant_id: 'tenant-1', type: 'color', name: 'Base Médio 2', value: 'Médio 2', extra: { hex: '#E5B898', price_modifier: 0 }, active: true },
  { id: 'opt-7', tenant_id: 'tenant-1', type: 'color', name: 'Base Escuro 1', value: 'Escuro 1', extra: { hex: '#B5805B', price_modifier: 0 }, active: true },
  
  // Tipos de Pele e Cabelo (Repurposed from "Tecido")
  { id: 'opt-9', tenant_id: 'tenant-1', type: 'fabric', name: 'Pele Oleosa', value: 'Pele Oleosa', extra: { description: 'Fórmula com controle de oleosidade', price_modifier: 0 }, active: true },
  { id: 'opt-10', tenant_id: 'tenant-1', type: 'fabric', name: 'Pele Seca', value: 'Pele Seca', extra: { description: 'Hidratação profunda e prolongada', price_modifier: 0 }, active: true },
  { id: 'opt-11', tenant_id: 'tenant-1', type: 'fabric', name: 'Pele Mista / Normal', value: 'Pele Mista/Normal', extra: { description: 'Nutrição equilibrada', price_modifier: 0 }, active: true },
  { id: 'opt-12', tenant_id: 'tenant-1', type: 'fabric', name: 'Cabelos Secos / Danificados', value: 'Cabelos Danificados', extra: { description: 'Reparação intensiva da fibra capilar', price_modifier: 0 }, active: true },
  { id: 'opt-13', tenant_id: 'tenant-1', type: 'fabric', name: 'Cabelos Oleosos', value: 'Cabelos Oleosos', extra: { description: 'Ação purificante e controle de oleosidade', price_modifier: 0 }, active: true },
  
  // Volumes e Dosagens (Repurposed from "Acabamento")
  { id: 'opt-14', tenant_id: 'tenant-1', type: 'finish', name: 'Frasco Regular 50ml', value: '50ml', extra: { price_modifier: 0 }, active: true },
  { id: 'opt-15', tenant_id: 'tenant-1', type: 'finish', name: 'Frasco Grande 100ml', value: '100ml', extra: { price_modifier: 45.00 }, active: true },
  { id: 'opt-16', tenant_id: 'tenant-1', type: 'finish', name: 'Versão de Bolsa 25ml', value: '25ml', extra: { price_modifier: -30.00 }, active: true },
  { id: 'opt-17', tenant_id: 'tenant-1', type: 'finish', name: 'Refil Econômico', value: 'Refil', extra: { price_modifier: -25.00 }, active: true },
  
  // Apresentações e Embalagens (Repurposed from "Tamanho")
  { id: 'opt-18', tenant_id: 'tenant-1', type: 'size', name: 'Embalagem Tradicional', value: 'Tradicional', extra: { price_modifier: 0 }, active: true },
  { id: 'opt-19', tenant_id: 'tenant-1', type: 'size', name: 'Embalagem de Presente Simples', value: 'Presente Simples', extra: { price_modifier: 10.00 }, active: true },
  { id: 'opt-20', tenant_id: 'tenant-1', type: 'size', name: 'Estojo Especial Rony Cosméticos', value: 'Estojo Especial', extra: { price_modifier: 25.00 }, active: true },
];

// ============================================================
// PRODUCTS
// ============================================================
export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    tenant_id: 'tenant-1',
    category_id: 'cat-1',
    name: 'Desodorante Colônia Luna Feminino (Natura)',
    slug: 'colonia-luna-feminino-natura',
    description: 'Luna celebra a beleza espontânea e autêntica de cada mulher com notas florais e um toque marcante de patchouli. Uma fragrância Chipre floral moderada que dura o dia todo na pele.',
    price: 149.90,
    price_from: 179.90,
    production_days: 1,
    is_featured: true,
    is_new: true,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/perfume-luna.jpg', alt: 'Perfume Luna Natura', order: 0 }],
    tags: ['perfume', 'feminino', 'natura', 'luna', 'colonia'],
    active: true,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prod-2',
    tenant_id: 'tenant-1',
    category_id: 'cat-1',
    name: 'Eau de Parfum Botica 214 Arabian (O Boticário)',
    slug: 'botica-214-arabian-oboticario',
    description: 'Fragrância refinada e marcante que combina com maestria o calor sofisticado da lavanda com o abraço caloroso do âmbar. Uma verdadeira viagem olfativa com o requinte que você merece.',
    price: 189.90,
    production_days: 1,
    is_featured: true,
    is_new: false,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/perfume-boticario.jpg', alt: 'Botica 214 Arabian', order: 0 }],
    tags: ['perfume', 'masculino', 'boticario', 'botica-214', 'fragrancia'],
    active: true,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'prod-3',
    tenant_id: 'tenant-1',
    category_id: 'cat-2',
    name: 'Batom Matte Glam Alta Fixação (Eudora)',
    slug: 'batom-matte-glam-eudora',
    description: 'Proporciona lábios coloridos com efeito matte aveludado impecável. Possui alta pigmentação e fixação de longa duração, deslizando confortavelmente sem ressecar seus lábios.',
    price: 44.90,
    price_from: 54.90,
    production_days: 1,
    is_featured: true,
    is_new: false,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/maquiagem-batom.jpg', alt: 'Batom Matte Eudora', order: 0 }],
    tags: ['batom', 'matte', 'maquiagem', 'eudora', 'boca'],
    active: true,
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'prod-4',
    tenant_id: 'tenant-1',
    category_id: 'cat-3',
    name: 'Creme Desodorante Nutritivo Tododia Cereja e Avelã (Natura)',
    slug: 'creme-tododia-cereja-avela-natura',
    description: 'Nutrição prebiótica que se adapta às necessidades diárias da sua pele. Sua fórmula especial com manteiga de cacau e óleo de linhaça penetra profundamente dando firmeza e maciez.',
    price: 69.90,
    production_days: 1,
    is_featured: false,
    is_new: true,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/cuidados-creme.jpg', alt: 'Hidratante Tododia Cereja e Avelã', order: 0 }],
    tags: ['creme', 'hidratante', 'corpo', 'natura', 'tododia'],
    active: true,
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'prod-5',
    tenant_id: 'tenant-1',
    category_id: 'cat-4',
    name: 'Sérum Concentrado Clareador Routine (Hinode)',
    slug: 'serum-clareador-routine-hinode',
    description: 'Sérum facial Routine enriquecido com Vitamina C estabilizada e Ácido Hialurônico. Reduz rugas finas, linhas de expressão, devolvendo a luminosidade e combatendo manchas.',
    price: 119.90,
    price_from: 139.90,
    production_days: 1,
    is_featured: false,
    is_new: true,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/routine-serum.jpg', alt: 'Sérum Clareador Routine Hinode', order: 0 }],
    tags: ['serum', 'skincare', 'hinode', 'rosto', 'vitamina-c'],
    active: true,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'prod-6',
    tenant_id: 'tenant-1',
    category_id: 'cat-6',
    name: 'Kit Presente Tododia Cereja e Avelã Completo',
    slug: 'kit-presente-tododia-cereja-avela',
    description: 'O presente completo ideal para demonstrar afeto. Contém: 1 Creme Nutritivo Corporal 400ml, 1 Caixa de Sabonetes em Barra (5 unidades) e 1 Body Splash Perfumado 200ml. Acompanha embalagem especial de presente.',
    price: 139.90,
    price_from: 169.90,
    production_days: 1,
    is_featured: true,
    is_new: false,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/kit-presente.jpg', alt: 'Kit Presente Tododia Natura', order: 0 }],
    tags: ['kit', 'presente', 'natura', 'tododia', 'cereja'],
    active: true,
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'prod-7',
    tenant_id: 'tenant-1',
    category_id: 'cat-5',
    name: 'Shampoo Siàge Nutri Ouro Fortalecedor (Eudora)',
    slug: 'shampoo-siage-nutri-ouro-eudora',
    description: 'Enriquecido com partículas de ouro e óleo de amaranto, o shampoo Siàge Nutri Ouro limpa suavemente enquanto repõe a massa capilar, garantindo cabelos 3x mais resistentes e super nutridos.',
    price: 39.90,
    production_days: 1,
    is_featured: false,
    is_new: false,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/shampoo-siage.jpg', alt: 'Shampoo Siàge Nutri Ouro', order: 0 }],
    tags: ['shampoo', 'siage', 'cabelo', 'eudora', 'nutri-ouro'],
    active: true,
    created_at: '2026-01-25T00:00:00Z',
    updated_at: '2026-01-25T00:00:00Z',
  },
  {
    id: 'prod-8',
    tenant_id: 'tenant-1',
    category_id: 'cat-2',
    name: 'Base Líquida Matte TimeWise 3D (Mary Kay)',
    slug: 'base-timewise-3d-mary-kay',
    description: 'Com o exclusivo complexo Age Minimize 3D, a base TimeWise 3D oferece acabamento matte e controle de oleosidade por até 12 horas. Disponível em diversos tons que combinam perfeitamente com a sua pele.',
    price: 79.90,
    production_days: 1,
    is_featured: false,
    is_new: true,
    is_customizable: true,
    is_made_to_order: false,
    images: [{ url: '/images/base-marykay.jpg', alt: 'Base TimeWise 3D Mary Kay', order: 0 }],
    tags: ['base', 'timewise', 'mary-kay', 'maquiagem', 'rosto'],
    active: true,
    created_at: '2026-02-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
];

// ============================================================
// INSPIRATIONS (Linhas / Coleções / Campanhas)
// ============================================================
export const mockInspirations: Inspiration[] = [
  {
    id: 'insp-1',
    tenant_id: 'tenant-1',
    title: 'Rotina de Skincare Perfeita',
    description: 'Passo a passo para manter a pele limpa, tonificada, hidratada e com aquela luminosidade natural radiante.',
    image_url: '/images/insp-skincare.jpg',
    product_ids: ['prod-5', 'prod-8', 'prod-4'],
    active: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'insp-2',
    tenant_id: 'tenant-1',
    title: 'Fragrâncias Irresistíveis',
    description: 'Uma seleção de colônias e perfumes femininos e masculinos que marcam presença em qualquer ocasião especial.',
    image_url: '/images/insp-perfumes.jpg',
    product_ids: ['prod-1', 'prod-2', 'prod-6'],
    active: true,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'insp-3',
    tenant_id: 'tenant-1',
    title: 'Make Completa e Iluminada',
    description: 'Produtos de maquiagem essenciais para criar desde uma pele leve para o dia a dia até um visual sofisticado de festa.',
    image_url: '/images/insp-make.jpg',
    product_ids: ['prod-3', 'prod-8', 'prod-7'],
    active: true,
    created_at: '2026-02-01T00:00:00Z',
  },
];

// ============================================================
// TESTIMONIALS (Depoimentos)
// ============================================================
export const mockTestimonials = [
  {
    id: 't-1',
    name: 'Fernanda Oliveira',
    location: 'São Paulo, SP',
    text: 'A colônia Luna da Natura chegou super rápida e muito bem embalada! O atendimento de Rony Cosméticos via WhatsApp foi excelente e me ajudou a escolher a fragrância ideal. Com certeza comprarei mais.',
    avatar: 'FO',
    rating: 5,
  },
  {
    id: 't-2',
    name: 'Carolina Mendes',
    location: 'Rio de Janeiro, RJ',
    text: 'Comprei o kit de presente Tododia de Cereja e Avelã para o aniversário da minha mãe. Ela adorou! A caixa de presente é linda e os produtos de altíssima qualidade. O envio foi imediato.',
    avatar: 'CM',
    rating: 5,
  },
  {
    id: 't-3',
    name: 'Mariana Costa',
    location: 'Curitiba, PR',
    text: 'A base TimeWise 3D da Mary Kay é simplesmente maravilhosa, tem uma cobertura mate impecável. A vendedora foi um amor, enviou amostras grátis e me deu ótimas dicas de tons.',
    avatar: 'MC',
    rating: 5,
  },
  {
    id: 't-4',
    name: 'Juliana Souza',
    location: 'Belo Horizonte, MG',
    text: 'A linha Siàge da Eudora salvou meu cabelo capilar. Os preços da loja do Rony são ótimos e a entrega é super pontual. Já virei cliente fiel de toda a linha de cosméticos!',
    avatar: 'JS',
    rating: 5,
  },
];
